### ISSUE TITLE
"git submodule init" not working on macOS

### ISSUE THREAD

**Issue by eduardfrigola** [danzeeeman/ofxVVISF#1]
System: macOS (10.13.6).
OF in master branch, commit: https://github.com/openframeworks/openFrameworks/commit/0e0a59fcc35bcbb5e2078163c1b607c57afd351f

Seems that git cannot find the submodules.
Replacing "\\" with "/" as separator did the trick.

I don't know too much about git to say that is the way has to be, but at least seems to be the case for my setup.

**Comment by danzeeeman** [comment]
this was created on windows

**Comment by danzeeeman** [comment]
fixed submodules config
